
# Netlify configuration file

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Ensure proper handling of SPA routes
[[headers]]
  for = "/*"
    [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Add long cache for static assets
[[headers]]
  for = "/*.js"
    [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
    [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/lovable-uploads/*"
    [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "image/jpeg, image/png, image/webp"

[[headers]]
  for = "/*.woff2"
    [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.webp"
    [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Compression for better performance
[[headers]]
  for = "/*.(js|css|html|svg|webp|jpg|png)"
    [headers.values]
    Content-Encoding = "br, gzip"

# Security headers to improve performance score
[[headers]]
  for = "/*"
    [headers.values]
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer-when-downgrade"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

# Set correct content type for images to prevent issues
[[headers]]
  for = "/*.jpg"
    [headers.values]
    Content-Type = "image/jpeg"

[[headers]]
  for = "/*.png"
    [headers.values]
    Content-Type = "image/png"

[[headers]]
  for = "/*.webp"
    [headers.values]
    Content-Type = "image/webp"
