
# Netlify configuration file

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Ensure proper handling of SPA routes
[[headers]]
  for = "/*"
    [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Add long cache for static assets
[[headers]]
  for = "/*.js"
    [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
    [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/lovable-uploads/*"
    [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.woff2"
    [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.webp"
    [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Compression for better performance
[[headers]]
  for = "/*.(js|css|html|svg|webp|jpg|png)"
    [headers.values]
    Content-Encoding = "br, gzip"
